
export const SCHEDULE_UPDATE_FIELD = 'SCHEDULE_UPDATE_FIELD'

export const SCHEDULE_LOADING_REQUEST = 'SCHEDULE_LOADING_REQUEST'
export const SCHEDULE_LOADING_SUCCESS = 'SCHEDULE_LOADING_SUCCESS'
export const SCHEDULE_LOADING_ERROR = 'SCHEDULE_LOADING_ERROR'

export const SCHEDULE_IMPORT_LOADING_REQUEST = 'SCHEDULE_IMPORT_LOADING_REQUEST'
export const SCHEDULE_IMPORT_LOADING_SUCCESS = 'SCHEDULE_IMPORT_LOADING_SUCCESS'
export const SCHEDULE_IMPORT_LOADING_ERROR = 'SCHEDULE_IMPORT_LOADING_ERROR'

export const SCHEDULE_SAVING_REQUEST = 'SCHEDULE_SAVING_REQUEST'
export const SCHEDULE_SAVING_SUCCESS = 'SCHEDULE_SAVING_SUCCESS'
export const SCHEDULE_SAVING_ERROR = 'SCHEDULE_SAVING_ERROR'
